### ISSUE TITLE
sqlalchemy.orm.Mapped[UUID] isn't supported

### ISSUE THREAD

**Issue by sh-at-cs** [dataclass-mapper/dataclass-mapper#31]
## Steps to reproduce

Consider:

```python
from dataclasses import dataclass
from uuid import UUID

from dataclass_mapper import create_mapper
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Pure Python model

@dataclass
class A:
    id: UUID

# SQLAlchemy models

class Base(DeclarativeBase):
    pass

class OrmA(Base):
    __tablename__ = "a"

    id: Mapped[UUID] = mapped_column(primary_key=True)

# Mapper

create_mapper(A, OrmA)
```

This results in an exception:

```python
NotImplementedError: type 'CHAR(32)' of field 'id' is not supported
```

## Expected behavior

Because SQLAlchemy type annotations of `Mapped[X]` just mean that the type of the field will be `X` in Python, it should just generate a mapper that maps the UUID as-is.

## Other notes

I don't know enough about SQLAlchemy internals and how dataclass-mapper accesses them to understand why `CHAR(32)` turns up here, but I can see how that might make things very difficult :grimacing: Maybe the annotation itself should have precedence over whatever SQLAlchemy internals are currently used?

```python
>>> print(OrmA.__annotations__)
{'id': sqlalchemy.orm.base.Mapped[uuid.UUID]}
```

## Version info

Tested in version 2.0.0a1.

## Related issues

- #5

**Comment by jakobkogler** [comment]
Thanks for the detailed issue description.

The problem is, that quite a lot of databases don't have native support as UUIDs, e.g. SQLite just stores the id into a text field (`CHAR(32)`).
However SQLAlchemy does all the heavy lifting for us. When you store or query an entity with such a type, SQLAlchemy converts the type automatically.

I've enabled it, that UUIDs are now supported.
Your example works now with [Release 2.0.0a2](https://github.com/dataclass-mapper/dataclass-mapper/releases/tag/v2.0.0a2).

**Comment by sh-at-cs** [comment]
Thanks!! :+1:
