### ISSUE TITLE
[bug] Not compat with `from __future__ import annotations`

### ISSUE THREAD

**Issue by filwaline** [dataclass-mapper/dataclass-mapper#9]
Very easy to reproduce, just add `from __future__ import annotations` at first line, and BOOOOOM!

**Comment by filwaline** [comment]
I have facing some circular dependency problem, so I am trying add `from __future__ import annotations` to resovle it...

Circular dependency problem resovled, and dataclass-mapper crash...... 

This one also produce very confusing error message, it take me times to figure out what make dataclass-mapper crash......

Not in hurry, just reporting.

**Comment by jakobkogler** [comment]
That's kinda expected. `from __future__ import annotations` converts all type annotations into strings, and it's really hard to extract the correct types.
Pydantic does some magic to extract the types, but also has trouble doing it from time to time.
And for Python's standard lib dataclasses, you just get the strings.

Maybe it's possible to extract the types with `typing.get_type_hints()` (never used it before, so I'm not sure about it's limitations).

But in general, if it's not easy to extract the types via standard library tools, this library will not support `from __future__ import annotations` (or annotating class attributes with strings instead of the actual types).

If you have circular dependency problems, you should try to organize your code to be non-circular, instead of hiding the problem with `from __future__ import annotations`.

**Comment by filwaline** [comment]
```python
import strawberry
from typing import List

from dataclass_mapper import map_to, mapper_from,mapper
from pydantic import BaseModel


@strawberry.type
class User:
    id: str

    @strawberry.field
    def reviews(self) -> List["Review"]:
        ...



@strawberry.type
class Review:
    id: str
    user: User

@mapper_from(User)
@mapper(User)
class UserInDb(BaseModel):
    id: str

@mapper_from(Review)
@mapper(User)
class ReviewInDb(BaseModel):
    id: str
    user: UserInDb



@strawberry.type
class Query:
    _hi: str



schema = strawberry.Schema(query=Query)
```

Using string annotations breaks too, same problem like `from __future__ import annotations`?

strawberry-graphql heavy rely on type annoations, so circular dependency never going to disappear, maybe i just have to let dataclass-mapper go away sometimes...
